# Generated by Django 4.2.29 on 2026-03-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='followed_organizers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.organizerprofile'),
        ),
    ]
